### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by code4cake** [72/bodymovin-for-Framer#4]
Hey man, question, I'm about to use this module, but I have a question, the `images.json`are those images created in Adobe After Effects? Is there a work around to this, i.e, for people who cannot "Adobe After Effects" by using other tools such as framer, affinity design, etc? 

Thanks.

I'm new to this.

**Comment by 72** [comment]
Hey @dantesolis ,

Yes, the JSON files are created in After Effects. 

[Lottie](https://airbnb.design/lottie/) runs JSONs files exported through [Bodymovin](https://aescripts.com/bodymovin/), which is an After Effects plugin.

An alternative to using AfterEffects+Bodymovin is [Haiku](https://www.haiku.ai/). But depending on what you're tying to do, you may still need to use Lottie to run the exported JSON file.

I'm closing this issue as it is not an issue, but a question.
For any additional questions please contact me directly and I'll be happy to help.
